version: "3.9"

services:
  #MongoDB service
  mongo_db:
    container_name: mongo_db_bp
    image: mongo:latest
    restart: always
    ports:
      - 2718:27017
    volumes:
      - mongo_db:/data/db

  #NestJS api-urls service
  api_urls:
    build: .
    ports:
      - 4000:12345
    volumes:
      - .:/usr/src/app
    environment:
      PORT: ${PORT}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_DB_URI: ${MONGO_DB_URI}

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
